### PR TITLE
Add kaolin-bubblegum for wezterm.

### PR DESCRIPTION
**Pull request by theherk**
This adds color scheme toml and recommended retro tab bar configuration.
This part is totally optional, but provides some nice defaults if users
choose.

### CODE REVIEW

**Comment by theherk** [comment]
Screenshot 2022-06-15 at 20 57 36

**Comment by alternateved** [comment]
Hello @theherk,

That looks really good! Amazing job on styling the tab bar. I've tested in on Linux and colors look equally good. 

The only thing that I would change; would you mind making the default cursor color white, to stay close to the original? And then keep the blue option keep commented out (as it really plays nice with the theme)?

**Comment by theherk** [comment]
@alternateved Not a problem at all; I meant to in the first place, but I forgot to swap them when I copied this from my configuration.

**Comment by alternateved** [comment]
Thank you for your contribution!

**Pull request merged**
